# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Close Master Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  bump:
    runs-on: ubuntu-latest
    name: Bump patch version
    if: contains(github.head_ref, 'hotfix')
    env:
      GITHUB_USER: "os-jsplopes"
      GITHUB_EMAIL: "julio.lopes@outsystems.com"

    steps:
      - uses: actions/checkout@v2
      - name: Setup git
        run: |
          git config --global user.name $GITHUB_USER
          git config --global user.email $GITHUB_EMAIL
      #- name: Bump patch version
      #  run: |
      #    npm version patch
      #    git push --tags origin HEAD:master
      #- name: Publish
      #  run: npm publish --tag release
