#Workflow tah will trigger a draft pull request creation on master branch

name: Hotfix

on:
  push:
    branches: [hotfix/*, release/*]

jobs:
  build-and-deploy:
    name: Build and Publish hotfix package
    runs-on: ubuntu-latest
    # Set this vars on project secrets
    env:
      GITHUB_USER: "os-jsplopes"
      GITHUB_EMAIL: "julio.lopes@outsystems.com"

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@${{env.GITHUB_USER}}"

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get Branch Name
        id: branch
        uses: ypicard/get-branch-name-github-action@v1

      - run: echo "$TEST"
        env:
          TEST: ${{ toJson(steps.branch.outputs) }}

      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./package.json

      - run: echo "$VERSION"
        env:
          VERSION: ${{ steps.package.outputs.version }}

      - name: Set Version
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: version
          VALUE: "v$VERSION-hotfix"
          FILE: package.json
      - name: Bump version
        run: |
          git config --global user.name $GITHUB_USER
          git config --global user.email $GITHUB_EMAIL
      #    npm version patch
      #    git push --tags origin HEAD:master
      - name: Publish
        run: npm publish --tag hotfix
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-pull-request:
    needs: [build-and-deploy]
    name: Create pull request on master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Read template
        id: pr_template
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.github/PULL_REQUEST_TEMPLATE.md
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Hotfix: ${{github.event.head_commit.message}}"
          pr_body: ${{steps.pr_template.outputs.content}}
          pr_assignee: ${{github.actor}}
          pr_label: "WIP,bug"
          pr_draft: true
          github_token: ${{ secrets.GAT }}
