# Workflow that will trigger the build validation
# if succeded deploy a package for testing and
# then create or update a pull request on master branch

name: Hotfix

on:
  push:
    branches: [hotfix/*, release/*]

jobs:
  build-and-deploy:
    name: Build and Publish hotfix package
    runs-on: ubuntu-latest
    # Set this vars on project secrets
    env:
      GITHUB_USER: "os-jsplopes"
      GITHUB_EMAIL: "julio.lopes@outsystems.com"

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@${{env.GITHUB_USER}}"

      - name: Read Branch Name
        id: branch
        uses: ypicard/get-branch-name-github-action@v1

      - name: Read Current Version
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version

      - name: Set Version
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          KEY: version
          VALUE: "${{ steps.package-version.outputs.version }}-hotfix.${{ github.event.repository.id }}"
          FILE: package.json

      - name: Testaa
        uses: octokit/graphql-action@v2.x
        id: get_package_id
        with:
          query: |
            query($owner:String!, $reponame:String!) {
              repository(owner:$owner, name:$reponame) {
                 packages(names: [$reponame], last: 1) {
                  totalCount
                }
              }
            }
          owner: "${{ github.event.repository.owner.name }}"
          reponame: "${{ github.event.repository.name }}"
          headers: '{ "accept": "application/vnd.github.package-preview+json" }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "${{ toJson(steps.get_package_id.outputs) }}"

      - name: Delete Previous Package Publication
        uses: actions/delete-package-versions@v1
        with:
          package-version-ids: ${{ steps.get_package_id.outputs }}
          token: ${{ secrets.GAT }}

      - name: Publish
        run: npm publish --tag hotfix.${{ github.event.repository.id }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-update-pull-request:
    needs: [build-and-deploy]
    name: Create/Update pull request on master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Read pull request template
        id: pr_template
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.github/PULL_REQUEST_TEMPLATE.md
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          pr_title: "Hotfix: ${{github.event.head_commit.message}}"
          pr_body: ${{steps.pr_template.outputs.content}}
          pr_assignee: ${{github.actor}}
          pr_label: "WIP,bug"
          pr_draft: true
          github_token: ${{ secrets.GAT }}
