# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [ master ]
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        GITHUB_USER: "os-jsplopes"
        GITHUB_EMAIL: "julio.lopes@outsystems.com"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: "12.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@jsplopes"
    - name: Bump version
      if: contains(${{github.head_ref}}, "hotfix")
      run: |
          git config --global user.name $GITHUB_USER
          git config --global user.email $GITHUB_EMAIL
          npm version patch
          git push --tags hotfix
    - name: Publish package
      run: npm publish --tag "aaa"
  merge-PR:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context         
        run: 'echo "$GITHUB_CONTEXT"'
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
         
