name: Pull Request

on:
  pull_request_review:
    branches: [master]
  pull_request_review_comment:
    branches: [master]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Labeler
    steps:
      - uses: actions/checkout@master
      - name: labeler
        uses: estrada9166/labeler@v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CONFIG_PATH: ../labeler-config.yml
