# Workflow that will trigger the build & test validations
# then create or update a pull request on master branch

name: Push To Master

on:
  push:
    branches:
      - master

jobs:
  hotfix:
    name: Create Github Tag
    if: contains(github.event.head_commit.message, 'hotfix')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup git
        run: |
          git config --global user.name ${{github.event.pusher.name}}
          git config --global user.email ${{github.event.pusher.email}}
      - name: Bump patch version
        run: |
          npm version patch
          printf "\n\n$(date)" >> README.md
          git add .
          git commit -m "bump patch version" -a
      - name: Push patch version
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GAT }}
          tags: true
      #- name: Create patch
      #  run: git push --tags origin HEAD:master
