# Workflow that will trigger the build & test validations
# then create or update a pull request on master branch

name: Push To Master

on:
  push:
    branches:
      - master

jobs:
  hotfix:
    name: Create Github Tag
    if: contains(github.head_commit.message, 'hotfix')
    runs-on: ubuntu-latest

    steps:
      - run: echo ${{toJson(github)}}
      - uses: actions/checkout@v2
      - name: Setup git
        run: |
          git config --global user.name ${{github.pusher.author.username}}
          git config --global user.email ${{github.pusher.author.email}}
      - name: Bump patch version
        run: |
          npm version patch
          git add .
          git commit -m "bump patch version"
          git push --tags origin HEAD:master
