# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Ready 4 Review Master Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - ready_for_review

jobs:
  label:
    runs-on: ubuntu-latest
    name: Update PR Label

    steps:
      - uses: actions/checkout@v2
      #- name: Bump patch version
      #  run: |
      #    npm version patch
      #    git push --tags origin HEAD:master
      #- name: Publish
      #  run: npm publish --tag release
