# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sync Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - synchronize

jobs:
  validate-build:
    runs-on: ubuntu-latest
    name: Validate Build and Tests Run
    if: (contains(github.head_ref, 'hotfix') || contains(github.head_ref, 'release'))

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
