# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Validate Pull Request

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    if: (contains(github.head_ref, 'hotfix') || contains(github.head_ref, 'release')) == false

    steps:
      - name: Automatic pull request review
        uses: thollander/actions-comment-pull-request@1.0.0
        with:
          # Message that should be printed in the pull request
          message: |
            ## :rotating_light: Invalid Pull Request :rotating_light:
            Invalid source branch **develop**.
            The master branch only accept pull requests from **Hotfix** or **Release** branches.
            **Please close the pull request!**
            :thinking::raising_hand_man::point_up:
          # Github token of the repository (automatically created by Github)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: exit 1

  build:
    runs-on: ubuntu-latest
    if: (contains(github.head_ref, 'hotfix') || contains(github.head_ref, 'release'))

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
